force-app/main/CSLogger/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Log Object to catch successes and errors</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/CSLogger/objects/Log__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>Class Name attribute to this action</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/CSLogger/objects/Log__c/fields/JSON__c.field-meta.xml
<CustomField>
    <fullName>JSON__c</fullName>
    <description>JSON String (for debugging API calls)</description>
    <label>JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Logging Level for this action</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/CSLogger/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message for this action</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/objects/Log__c/fields/ObjectIDs__c.field-meta.xml
<CustomField>
    <fullName>ObjectIDs__c</fullName>
    <description>Comma delimited list of Object ID&#39;s affected by this action</description>
    <label>Object IDs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/objects/Log__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <description>Object Name being saved in this action (for DML)</description>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/CSLogger/objects/Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Stack Trace (for exceptions)</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/objects/Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that initiated this action</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/CSLogger/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <description>Platform Event to capture Logs</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/CSLogger/objects/LogEvent__e/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>Class Name attribute to this action</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/CSLogger/objects/LogEvent__e/fields/JSON__c.field-meta.xml
<CustomField>
    <fullName>JSON__c</fullName>
    <description>JSON String (for debugging API calls)</description>
    <label>JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/objects/LogEvent__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Logging Level for this action</description>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/CSLogger/objects/LogEvent__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message for this action</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/objects/LogEvent__e/fields/ObjectIDs__c.field-meta.xml
<CustomField>
    <fullName>ObjectIDs__c</fullName>
    <description>Comma delimited list of Object ID&#39;s affected by this action</description>
    <label>Object IDs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/objects/LogEvent__e/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <description>Object Name being saved in this action (for DML)</description>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/CSLogger/objects/LogEvent__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Stack Trace (for exceptions)</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/classes/LogToObject.cls
public with sharing class LogToObject implements ILogWriter {
    public LogToObject() {

    }

    /**
     * Write to the actual Log object from a Platform Event trigger
     * @param  logEvents Trigger.new from the Log Event trigger
     */
    public void write(List<LogEvent__e> logEvents) {
        List<Log__c> logs = new List<Log__c>();

        for (LogEvent__e le : logEvents) {
            logs.add(
                new Log__c(
                    ClassName__c = le.ClassName__c,
                    Level__c = le.Level__c,
                    ObjectName__c = le.ObjectName__c,
                    ObjectIDs__c = le.ObjectIDs__c,
                    Message__c = le.Message__c,
                    StackTrace__c = le.StackTrace__c,
                    JSON__c = le.JSON__c,
                    User__c = le.CreatedById
                )
            );
        }

        if (!logs.isEmpty()) {
            // We don't give users access to create log entries manually, so ignore CRUD/FLS here
            // Data.create(logs, false, false, false);
            insert logs;
        }
    }
}