force-app/main/CRUDFLS/objects/DebugSettings__c/DebugSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to declaratively enable/disable debugging features.</description>
    <label>Debug Settings</label>
</CustomObject>

force-app/main/CRUDFLS/objects/DebugSettings__c/fields/EnableLimitsSnapshot__c.field-meta.xml
<CustomField>
    <fullName>EnableLimitsSnapshot__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Limits Snapshot</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/CRUDFLS/classes/LimitsSnapshotTest.cls
@isTest
private class LimitsSnapshotTest {
	@isTest
	static void itShould() {

		DebugSettings__c settings = DebugSettings__c.getInstance();
		settings.EnableLimitsSnapshot__c = true;
		upsert settings;

		//
		Test.startTest();
		LimitsSnapshot ls = new LimitsSnapshot('Apex Test');
		ls.toLog();
		ls.toLog(null);
		ls.toDatabase();
		Test.stopTest();

		System.assertNotEquals(null, ls.getLimitStart(LimitsSnapshot.LimitEnum.CpuTime));
		System.assertNotEquals(null, ls.getLimitEnd(LimitsSnapshot.LimitEnum.CpuTime));
	}

	@isTest
	static void remainingCoverage() {
		LimitsSnapshot ls = new LimitsSnapshot();
		ls.toLog();

		System.assert(true);
	}
}